/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5d471e52a8e9561a0d35d2
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// COURSE
export const RESET_COURSE = "RESET_COURSE";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const LIST_COURSE_SUCCESS = "LIST_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";

// EVENTS
export const RESET_EVENTS = "RESET_EVENTS";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const FINDBY_STUDENT_EVENTS_SUCCESS = "FINDBY_STUDENT_EVENTS_SUCCESS";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const LIST_EVENTS_SUCCESS = "LIST_EVENTS_SUCCESS";
export const UPDATE_EVENTS_SUCCESS = "UPDATE_EVENTS_SUCCESS";

// STUDENT
export const RESET_STUDENT = "RESET_STUDENT";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const LIST_STUDENT_SUCCESS = "LIST_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// TEACHER
export const RESET_TEACHER = "RESET_TEACHER";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const FINDBY_COURSE_TEACHER_SUCCESS = "FINDBY_COURSE_TEACHER_SUCCESS";
export const FINDBY_STUDENT_TEACHER_SUCCESS = "FINDBY_STUDENT_TEACHER_SUCCESS";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const LIST_TEACHER_SUCCESS = "LIST_TEACHER_SUCCESS";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
